// Builds dist/ for Cloudflare Pages. dist/tapdot-editor.js is the whole editor in one file, for hosting on Squarespace
// (or anywhere) and loading from a code block. Run with `node tools/build.js` after changing
// index.html or anything in editor/.
//
// The file draws the editor inside an iframe so the site's own styles can't leak into it.
// The iframe uses srcdoc, so it shares the site's origin and autosave (localStorage) still works.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const read = (f) => fs.readFileSync(path.join(root, f), 'utf8');
const noClose = (s, tag) => s.replace(new RegExp('</' + tag, 'gi'), '<\\/' + tag);

let html = read('index.html');
html = html.replace(/<link rel="stylesheet" href="([^"]+)"\s*\/?>/g, (m, f) => '<style>\n' + noClose(read(f), 'style') + '\n</style>');
html = html.replace(/<script src="([^"]+)"><\/script>/g, (m, f) => '<script>\n' + noClose(read(f), 'script') + '\n</script>');
if (/<script src=|<link rel="stylesheet"/.test(html)) throw new Error('index.html still references an external file');

// Keep the file pure ASCII so it decodes the same whatever charset the host serves it with.
const ascii = (s) => s.replace(/[\u007f-\uffff]/g, (c) => '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0'));

const out = `/* TapDot Editor, single-file build (generated by tools/build.js; do not edit by hand). */
(function () {
  var HTML = ${ascii(JSON.stringify(html))};
  var me = document.currentScript;
  function mount() {
    var host = document.getElementById('tapdot-editor');
    if (!host) { host = document.createElement('div'); me.parentNode.insertBefore(host, me); }
    if (host.getAttribute('data-mounted')) return;
    host.setAttribute('data-mounted', '1');
    var f = document.createElement('iframe');
    f.title = 'TapDot Editor';
    f.setAttribute('allow', 'clipboard-read; clipboard-write; fullscreen');
    f.style.cssText = 'display:block;width:100%;border:0;border-radius:0;background:#0f1115;height:' +
      (host.getAttribute('data-height') || 'max(640px, 92vh)');
    f.srcdoc = HTML;
    host.appendChild(f);
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mount); else mount();
})();
`;
fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
fs.writeFileSync(path.join(root, 'dist/tapdot-editor.js'), out);
console.log('dist/tapdot-editor.js', Math.round(out.length / 1024) + ' KB');

// The client portal (served by Cloudflare Pages, with the API in functions/): the portal pages go
// to dist/app/, the editor as one page at dist/app/editor.html, and everything in public/ (the live
// page loader embed.js and the _headers file) to dist/.
const mkdir = (d) => fs.mkdirSync(path.join(root, d), { recursive: true });
mkdir('dist/app');
for (const f of fs.readdirSync(path.join(root, 'portal'))) fs.copyFileSync(path.join(root, 'portal', f), path.join(root, 'dist/app', f));
fs.writeFileSync(path.join(root, 'dist/app/editor.html'), html);
// The portal's New page picker draws template previews with the editor's own templates and renderer.
mkdir('dist/app/td');
for (const f of ['schema.js', 'render.js']) fs.copyFileSync(path.join(root, 'editor', f), path.join(root, 'dist/app/td', f));
for (const f of fs.readdirSync(path.join(root, 'public'))) fs.copyFileSync(path.join(root, 'public', f), path.join(root, 'dist', f));
console.log('dist/app/ (portal) and public/ files');
